// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pjmzsxeefmnqbwxxcrue.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBqbXpzeGVlZm1ucWJ3eHhjcnVlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYxMDI2MjMsImV4cCI6MjA2MTY3ODYyM30.gnEfoJNx3puS7NTGz1PRqiI_LIgf1ndEGgsQJj-BkcY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);